import type { VideoNews } from "./types"

const samples = [
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
]

export const videos: VideoNews[] = [
  {
    id: "v-climate-summit",
    title: "Inside the overnight Brussels climate deal",
    description:
      "How EU leaders reached a 90% emissions cut for 2040 — and which fights they postponed until the legislation.",
    thumbnailUrl: "/images/news/eu-flags.jpg",
    videoUrl: samples[0],
    duration: "6:18",
    publishedAt: "2026-08-29T07:05:00Z",
    category: "Europe",
    views: 214500,
    featured: true,
    author: "Emma Johnson",
  },
  {
    id: "v-heatwave",
    title: "Southern Europe's nights that will not cool",
    description: "From Athens to Seville, cities opened midnight cooling centres as August records fell.",
    thumbnailUrl: "/images/news/venice.jpg",
    videoUrl: samples[1],
    duration: "4:42",
    publishedAt: "2026-08-29T05:20:00Z",
    category: "Europe",
    views: 162300,
    featured: true,
    author: "Laura Rossi",
  },
  {
    id: "v-dma",
    title: "What the latest DMA fine means for your phone",
    description: "A plain-language guide to self-preferencing, app stores and the penalties now on the table.",
    thumbnailUrl: "/images/news/parliament.jpg",
    videoUrl: samples[2],
    duration: "7:05",
    publishedAt: "2026-08-28T19:10:00Z",
    category: "Technology",
    views: 98700,
    featured: true,
    author: "Michael Chen",
  },
  {
    id: "v-ucl-draw",
    title: "Champions League draw: Madrid vs Munich, night one",
    description: "Tactics, absences and why broadcasters already call it the game of September.",
    thumbnailUrl: "/images/news/stadium.jpg",
    videoUrl: samples[3],
    duration: "8:21",
    publishedAt: "2026-08-28T10:15:00Z",
    category: "Sports",
    views: 301200,
    featured: true,
    author: "David Martinez",
  },
  {
    id: "v-ecb",
    title: "Why the ECB stood still",
    description: "Inflation at 2.1%, a cautious Council, and what a hold means for mortgages and the euro.",
    thumbnailUrl: "/images/news/ecb.jpg",
    videoUrl: samples[4],
    duration: "5:44",
    publishedAt: "2026-08-28T15:00:00Z",
    category: "Business",
    views: 67400,
    author: "Sophie Dubois",
  },
  {
    id: "v-ai-code",
    title: "Europe's new rulebook for frontier AI",
    description: "Watermarks, training-data summaries and the first real test of the AI Act.",
    thumbnailUrl: "/images/news/parliament.jpg",
    videoUrl: samples[5],
    duration: "9:12",
    publishedAt: "2026-08-27T17:20:00Z",
    category: "Technology",
    views: 85900,
    author: "Thomas Weber",
  },
  {
    id: "v-wind-grid",
    title: "A power grid in the North Sea",
    description: "Six countries signed up to share offshore wind. Here is how the cables would actually work.",
    thumbnailUrl: "/images/news/wind.jpg",
    videoUrl: samples[6],
    duration: "6:50",
    publishedAt: "2026-08-27T12:00:00Z",
    category: "Europe",
    views: 54300,
    author: "Klaus Mueller",
  },
  {
    id: "v-diet",
    title: "Can a Mediterranean plate protect the brain?",
    description: "We walk through the Barcelona dementia study — and what it does not prove.",
    thumbnailUrl: "/images/news/food.jpg",
    videoUrl: samples[7],
    duration: "4:28",
    publishedAt: "2026-08-27T09:10:00Z",
    category: "Health",
    views: 112800,
    author: "Laura Rossi",
  },
  {
    id: "v-juice",
    title: "JUICE at Mars: a slingshot toward Jupiter",
    description: "ESA's icy-moons mission just used Mars for a gravity assist. Next stop, 2031.",
    thumbnailUrl: "/images/news/space.jpg",
    videoUrl: samples[8],
    duration: "8:05",
    publishedAt: "2026-08-26T16:00:00Z",
    category: "Science",
    views: 76800,
    author: "Lukas Schmidt",
  },
  {
    id: "v-fashion",
    title: "Mushroom leather and grape-waste bags on the Paris runway",
    description: "Highlights from a Fashion Week that treated materials as the main event.",
    thumbnailUrl: "/images/news/fashion.jpg",
    videoUrl: samples[9],
    duration: "5:33",
    publishedAt: "2026-08-25T18:20:00Z",
    category: "Lifestyle",
    views: 134600,
    author: "Isabelle Moreau",
  },
  {
    id: "v-deep-sea",
    title: "New life in the Hellenic Trench",
    description: "Bioluminescent jellyfish, cold-water coral and an ROV 4,500 metres down.",
    thumbnailUrl: "/images/news/deepsea.jpg",
    videoUrl: samples[10],
    duration: "6:40",
    publishedAt: "2026-08-25T11:00:00Z",
    category: "Science",
    views: 49200,
    author: "Andreas Dimitriou",
  },
  {
    id: "v-tourism",
    title: "Europe's record summer — and the cities pushing back",
    description: "Arrivals are up. Venice, Barcelona and Amsterdam are rewriting the rules.",
    thumbnailUrl: "/images/news/venice.jpg",
    videoUrl: samples[11],
    duration: "5:16",
    publishedAt: "2026-08-24T14:30:00Z",
    category: "Lifestyle",
    views: 88700,
    author: "Carlos Mendez",
  },
  {
    id: "v-chips",
    title: "Dresden's new foundry and the Chips Act bet",
    description: "Why Europe is building mature-node capacity first — and what that means for carmakers.",
    thumbnailUrl: "/images/news/parliament.jpg",
    videoUrl: samples[0],
    duration: "7:22",
    publishedAt: "2026-08-24T10:00:00Z",
    category: "Technology",
    views: 53100,
    author: "Sofia Bergman",
  },
  {
    id: "v-vuelta",
    title: "Red jersey changes hands in the Sierra Nevada",
    description: "Heat, gradients and a 38-second lead: the Vuelta's first real shake-up.",
    thumbnailUrl: "/images/news/stadium.jpg",
    videoUrl: samples[1],
    duration: "4:55",
    publishedAt: "2026-08-23T19:20:00Z",
    category: "Sports",
    views: 142900,
    author: "Marco Rossi",
  },
  {
    id: "v-iter",
    title: "400 seconds of plasma at ITER",
    description: "A fusion milestone in Cadarache — and the caveats scientists want you to hear.",
    thumbnailUrl: "/images/news/space.jpg",
    videoUrl: samples[2],
    duration: "8:48",
    publishedAt: "2026-08-21T10:30:00Z",
    category: "Science",
    views: 61500,
    author: "Lukas Schmidt",
  },
]
